# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='started')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='ended')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timemanager.Project')),
            ],
        ),
    ]
